name: WorldGuard
main: worldguard\WorldGuard
api: 3.0.0-ALPHA10
version: 0.0.1
author: Muqsit
website: https://github.com/Muqsit/WorldGuard
commands:
  worldguard:
    description: World guard commands.
    aliases: ["wg", "rg"]
